`timescale 1ns / 1ps

// SLIP special characters
`define SLIP_END     8'hC0
`define SLIP_ESC     8'hDB
`define SLIP_ESC_END 8'hDC
`define SLIP_ESC_ESC 8'hDD

// Message format
`define MSG_LENGTH 3'd6

`define MSGID_TELEMETRY        8'h01
`define MSGID_REGISTERS        8'h02
`define MSGID_CONTROL          8'h03
`define MSGID_LOAD_WORD_MOD0   8'h10
`define MSGID_LOAD_WORD_MOD1   8'h11
`define MSGID_LOAD_WORD_MOD2   8'h12
`define MSGID_LOAD_WORD_MOD3   8'h13
`define MSGID_LOAD_WORD_MOD4   8'h14
`define MSGID_LOAD_WORD_MOD5   8'h15
`define MSGID_VERIFY_WORD_MOD0 8'h20
`define MSGID_VERIFY_WORD_MOD1 8'h21
`define MSGID_VERIFY_WORD_MOD2 8'h22
`define MSGID_VERIFY_WORD_MOD3 8'h23
`define MSGID_VERIFY_WORD_MOD4 8'h24
`define MSGID_VERIFY_WORD_MOD5 8'h25

`define MSG_GROUP_LOAD   4'h1
`define MSG_GROUP_VERIFY 4'h2

`define REGISTERS_CMD_SET_HIST_IDX 8'h00

`define CONTROL_CMD_SET_CST_MODE      8'h00
`define CONTROL_CMD_ADVANCE           8'h01
`define CONTROL_CMD_STOP              8'h02
`define CONTROL_CMD_SET_CMD_INS_ADDR  8'h03
`define CONTROL_CMD_SET_CMD_DATA_ADDR 8'h04
`define CONTROL_CMD_SET_RESTART_MODE  8'h05
`define CONTROL_CMD_RESTART           8'h06
`define CONTROL_CMD_SET_COMPARE_MODE  8'h07
`define CONTROL_CMD_SET_DISPLAY_MODE  8'h08
`define CONTROL_CMD_DISPLAY_RESET     8'h09
